name: build

on:
  push:
    paths-ignore:
      - 'examples/**'
      - 'doc/**'
      - README.md

jobs:
  publish:
    runs-on: macos-10.15
    needs:
      - sdist

      - mac-py35
      - mac-py36
      - mac-py37
      - mac-py38

      - linux-py35-64bit
      - linux-py36-64bit
      - linux-py37-64bit
      - linux-py38-64bit

      - win-py35-64bit
      - win-py36-64bit
      - win-py37-64bit
      - win-py38-64bit

      # 32-bit recombine not available yet
#      - linux-py35-32bit
#      - linux-py36-32bit
#      - linux-py37-32bit
#      - linux-py38-32bit

#      - win-py35-32bit
#      - win-py36-32bit
#      - win-py37-32bit
#      - win-py38-32bit
    if: github.ref == 'refs/heads/release'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: output
        path: build/dist
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' # for twine
    - name: Upload distribution to PyPI.
      run: cd build && ./publish.sh ${{ secrets.pypi_password }} pypi

  sdist:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Source distribution
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build && ./sdist.sh
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/sdist

  # Mac
  mac-py35:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Build for Python 3.5
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/OSX && ./build-wheel.sh 3.5.5
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/OSX/output

  mac-py36:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Build for Python 3.6
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/OSX && ./build-wheel.sh 3.6.5
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/OSX/output

  mac-py37:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Build for Python 3.7
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/OSX && ./build-wheel.sh 3.7.0
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/OSX/output

  mac-py38:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Build for Python 3.8
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/OSX && ./build-wheel.sh 3.8.1
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/OSX/output

  # Linux
  linux-py35-64bit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/Linux && ./build-wheel.sh cp35-cp35m x86_64
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Linux/output

  linux-py36-64bit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/Linux && ./build-wheel.sh cp36-cp36m x86_64
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Linux/output

  linux-py37-64bit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/Linux && ./build-wheel.sh cp37-cp37m x86_64
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Linux/output

  linux-py38-64bit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        source build/git-preamble.sh ${{ secrets.recombine_login }}
        cd build/Linux && ./build-wheel.sh cp38-cp38 x86_64
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Linux/output

  # Windows
  win-py35-64bit:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
        cd build\Windows
        .\build-wheel.ps1 `
          -vs_version 14.1 `
          -arch 64 `
          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python35 `
          -py_installer 3.5.4/python-3.5.4-amd64.exe `
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Windows/output

  win-py36-64bit:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
        cd build\Windows
        .\build-wheel.ps1 `
          -vs_version 14.1 `
          -arch 64 `
          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python36 `
          -py_installer 3.6.5/python-3.6.5-amd64.exe `
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Windows/output

  win-py37-64bit:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
        cd build\Windows
        .\build-wheel.ps1 `
          -vs_version 14.1 `
          -arch 64 `
          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python37 `
          -py_installer 3.7.9/python-3.7.9-amd64.exe `
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Windows/output

  win-py38-64bit:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
        cd build\Windows
        .\build-wheel.ps1 `
          -vs_version 14.1 `
          -arch 64 `
          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python38 `
          -py_installer 3.8.1/python-3.8.1-amd64.exe `
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/Windows/output

#  linux-py35-32bit:
#    runs-on: ubuntu-18.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        source build/git-preamble.sh ${{ secrets.recombine_login }}
#        cd build/Linux && ./build-wheel.sh cp35-cp35m i686
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Linux/output

#  linux-py36-32bit:
#    runs-on: ubuntu-18.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        source build/git-preamble.sh ${{ secrets.recombine_login }}
#        cd build/Linux && ./build-wheel.sh cp36-cp36m i686
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Linux/output

#  linux-py37-32bit:
#    runs-on: ubuntu-18.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        source build/git-preamble.sh ${{ secrets.recombine_login }}
#        cd build/Linux && ./build-wheel.sh cp37-cp37m i686
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Linux/output

#  linux-py38-32bit:
#    runs-on: ubuntu-18.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        source build/git-preamble.sh ${{ secrets.recombine_login }}
#        cd build/Linux && ./build-wheel.sh cp38-cp38 i686
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Linux/output

#  win-py35-32bit:
#    runs-on: windows-2019
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
#        cd build\Windows
#        .\build-wheel.ps1 `
#          -vs_version 14.1 `
#          -arch 32 `
#          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python35-32 `
#          -py_installer 3.5.4/python-3.5.4.exe `
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Windows/output

#  win-py36-32bit:
#    runs-on: windows-2019
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
#        cd build\Windows
#        .\build-wheel.ps1 `
#          -vs_version 14.1 `
#          -arch 32 `
#          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python36-32 `
#          -py_installer 3.6.5/python-3.6.5.exe `
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Windows/output

#  win-py37-32bit:
#    runs-on: windows-2019
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
#        cd build\Windows
#        .\build-wheel.ps1 `
#          -vs_version 14.1 `
#          -arch 32 `
#          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python37-32 `
#          -py_installer 3.7.0/python-3.7.0.exe `
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Windows/output

#  win-py38-32bit:
#    runs-on: windows-2019
#    steps:
#    - uses: actions/checkout@v2
#    - name: Run build
#      run: |
#        bash .\build\git-preamble.sh ${{ secrets.recombine_login }}
#        cd build\Windows
#        .\build-wheel.ps1 `
#          -vs_version 14.1 `
#          -arch 32 `
#          -py_install_dir C:\Users\runneradmin\AppData\Local\Programs\Python\Python38-32 `
#          -py_installer 3.8.1/python-3.8.1.exe `
#    - uses: actions/upload-artifact@v2
#      with:
#        name: output
#        path: build/Windows/output
